### ISSUE TITLE
CompanyLogos break above 288.png

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#113]
This is probably a bug or limitation of the game itself, but MGT2 Mod Tool could workaround it. Basically, if you add too many publishers, when a publisher gets assigned an icon that is higher than 288.png, it doesn't get loaded by the game.

The way I encountered this limitation was like this:

1. Add a renamed (real name) publisher for each one of the game's publishers.
2. Set them as `replaces = "PublisherName"`
3. Since they are too many, starting from 197.png it will reach 296.png, breaking the last ones and any additional publisher that I may add after this.

I tried circunventing the problem by setting `requires_pictures = false` under each publisher definition with the hope that it would avoid loading `publisher_name_publisher_icon.png` and would use the provided `PIC = "number"`, letting me use the already existing icons from 0.png to 187.png (and I would simply have to manually replace the png files as with any other drag and drop mod).

Is there a way to disable the custom icons from loading so I can workaround it like that? Or another more elegant solution?

EDIT: I also just noticed that after importing all the publishers it is removing 188.png through 196.png unecessarily. Maybe that is the index range im missing from the end?

**Comment by laureegrd** [comment]
Confirmed: The issue is that MGT2 Mod tool is deleting 188.png through 196.png so the game doesn't load the last 9 icons. If you copy those .pngs, apply the mods, then copy them back manually, it works perfectly. Maybe MGT2 Mod Tool is outdated and still thinks there are 188 (0-187) default icons?

**Comment by LMH01** [comment]
Thanks for your report, I could verify that the problem was indeed caused by the tool thinking that there are only 188 default icons. Your digging was very helpful, thanks for that.
I have updated that number and made it configurable in the settings file. This way (as a workaround until the tool gets updated again) it can be updated later manually without the requirement of a new update.

I'm now working on implementing the fix (should not take too long). Could you please send me the mod files that you are trying to load (to double check that the fix really worked) (you can use Discord for that if you like, my discord Tag is LMH01
#1614?

**Comment by LMH01** [comment]
Here is an alpha build that includes the fix, could you please try if that indeed fixes your problems?

Link: [v4.7.1-alpha](https://github.com/LMH01/MGT2_Mod_Tool/releases/tag/v4.7.1-alpha)

If it works I will merge it in master and create full release.

**Comment by laureegrd** [comment]
It works :) restored initial backup from stable version, switched to the 4.7.1 alpha, reimported my mod and all the original icons stay there as expected. Thanks for the quick fix!

**Comment by LMH01** [comment]
No problem glad I could help, marking the issue as pending release.
