### ISSUE TITLE
Arcade System 500/800/1000 icons get deleted for no reason

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#127]
`4.9.0-beta4`

Importing this mod file that renames most platforms (but doesn't change their icons) makes the tool delete `ASB1.png`, `ASB2.png` and `ASB3.png` which correspond to the first 3 Arcade Systems.

This mod file does not even mess with Arcade Systems since they don't require a name change.

Note: the mod also renames npc_ips and publishers (and their CompanyLogos), but the bug ***should*** still be there if those are not imported or removed from the zip file (untested).

[real_names.zip](https://github.com/LMH01/MGT2_Mod_Tool/files/10924250/real_names.zip)

- The log never states `Deleting images for content Arcade System 500/800/1000`, so the tool is silently removing them.
- As far as I can tell, the entries for those platforms in `Platforms.txt` remain intact, as they should.
- Tested in a fresh install of both game and mod tool.

**Comment by LMH01** [comment]
I just tested it and I can't quite replicate the problem:

Everything works flawlessly when I do the following:
1. Create new Initial backup
2. Start Mod-Tool and import the extracted .zip file
3. Check box that allows modification of already existing content
4. Import works without problems
5. Check if the png files are missing, they are still there

Oddly what did not work properly was importing the .zip file. When I imported the .zip file (so that the tool needed to extract the files) some problems occurred, mainly that some image files are missing. So it seems like something either with the .zip file is broken or that the extraction method is broken somehow. This will have to be tested separately. I will create a new issue for that.

**Comment by laureegrd** [comment]
Could it be? Maybe try to rezip the files yourself and see if that causes the bug.

I am on Windows 11, running 7zip 22.01. The command I'm using to create the zip file is standard:
`7z a new_content.zip *.toml assets`

I do still have a hard time believing the zip file itself could be causing the issue, though. Weird.

**Comment by LMH01** [comment]
Can you please try to import the files without zipping them? You can just select the parent folder.

**Comment by LMH01** [comment]
Done, see #128
